"use client";

import { useState } from "react";
import StyleSwitcher from "@/app/components/StyleSwitcher";
import EasterEgg from "@/app/components/EasterEgg";
import {
  InstagramIcon,
  YouTubeIcon,
  TwitterIcon,
  RedditIcon,
  LinkedInIcon,
} from "@/app/components/Icons";

const PLATFORM_NOTES = {
  instagram: {
    title: "Instagram Connection",
    icon: <InstagramIcon className="icon-lg" />,
    tech: ["MCP", "Graph API"],
    note: "Agent de Gestion Sociale leverages the Model Context Protocol (MCP) to interface directly with the Instagram Graph API. The pipeline processes media binaries, resizes them to optimal 4:5 ratios, and dispatches them via Celery workers to ensure non-blocking publishing.",
  },
  youtube: {
    title: "YouTube Integration",
    icon: <YouTubeIcon className="icon-lg" />,
    tech: ["OAuth 2.0", "Data API v3"],
    note: "Video ingestion is fully automated. Metadata, tags, and timestamps are generated by the agent and scheduled through Celery. We use chunked resumable uploads to guarantee stability for 4K video distributions.",
  },
  twitter: {
    title: "Twitter / X Service API",
    icon: <TwitterIcon className="icon-lg" />,
    tech: ["MCP", "v2 API"],
    note: "Real-time threaded tweets are assembled in memory. Our agent uses MCP to fetch real-time trending context, drafts the thread, and pushes it to a Celery queue with strict rate-limit backoff handling.",
  },
  reddit: {
    title: "Reddit Automation",
    icon: <RedditIcon className="icon-lg" />,
    tech: ["PRAW", "Async"],
    note: "Subreddit targeting is handled via dynamic mapping. The agent assesses subreddit rules via the API, structures the markdown payload, and executes the post asynchronously.",
  },
  linkedin: {
    title: "LinkedIn Connector",
    icon: <LinkedInIcon className="icon-lg" />,
    tech: ["UGC API", "Celery"],
    note: "Professional long-form content is synthesized by the LLM and routed through the UGC API. Polls, articles, and multi-image carousels are constructed via our robust internal builder and scheduled.",
  },
};

export default function LandingPage() {
  const [activePlatform, setActivePlatform] = useState("instagram");

  return (
    <div className="landing">
      {/* ── Nav ── */}
      <nav className="landing-nav premium-glass">
        <div className="landing-nav-left"></div>
        <div className="landing-nav-right">
          <StyleSwitcher />
          <a href="/login" className="btn btn-primary" id="btn-initiate">
            SIGN IN
          </a>
        </div>
      </nav>

      {/* ── Hero ── */}
      <section className="hero" style={{ paddingBottom: "160px", position: "relative" }}>
        <h1 className="hero-title">
          <span className="hero-title-black">BUILDING SCALABLE</span>
          <br />
          <span className="hero-title-red">SOCIAL SOFTWARE</span>
          <br />
          <span className="hero-title-black">LAYER BY LAYER.</span>
        </h1>

        <div className="hero-subtitle-box premium-glass">
          <p>
            Agent de Gestion Sociale is an autonomous pipeline built for production. 
            Powered by Celery task queues and Model Context Protocol (MCP), it ships 
            your content across platforms without manual intervention.
          </p>
        </div>
        
        {/* Curve SVG Divider */}
        <div className="curve-divider">
          <svg viewBox="0 0 1200 120" preserveAspectRatio="none">
            <path d="M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z" className="curve-path"></path>
          </svg>
        </div>
      </section>

      {/* ── Documentation / Interactive Connectors ── */}
      <section className="connectors" id="architecture" style={{ background: "var(--bg-surface)", paddingTop: "80px", paddingBottom: "120px", position: "relative" }}>
        <h2 className="section-heading">ARCHITECTURE INTEGRATION</h2>
        
        <div className="interactive-platforms">
          <div className="platform-row">
            {/* Sidebar Buttons */}
            <div className="platform-icons">
              {Object.keys(PLATFORM_NOTES).map((key) => (
                <button
                  key={key}
                  className={`platform-btn ${activePlatform === key ? "active" : ""}`}
                  onClick={() => setActivePlatform(key)}
                >
                  {PLATFORM_NOTES[key].icon}
                  {key.charAt(0).toUpperCase() + key.slice(1)}
                </button>
              ))}
            </div>

            {/* Notes Panel */}
            <div className="platform-notes-panel premium-glass">
              <div className="notes-content" key={activePlatform}>
                <div className="notes-header">
                  {PLATFORM_NOTES[activePlatform].icon}
                  {PLATFORM_NOTES[activePlatform].title}
                </div>
                <div style={{ marginBottom: "24px" }}>
                  {PLATFORM_NOTES[activePlatform].tech.map((t) => (
                    <span key={t} className="tech-tag">{t}</span>
                  ))}
                </div>
                <p className="notes-body">
                  {PLATFORM_NOTES[activePlatform].note}
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Official Footer ── */}
      <footer className="official-footer">
        <div className="footer-grid">
          <div className="footer-brand">
            <div className="footer-logo cursive-brand">AGS Core</div>
            <p className="footer-tagline">
              The autopilot for production social media incidents. Built for robust, scalable distribution.
            </p>
          </div>
          <div className="footer-col">
            <h4>Product</h4>
            <ul>
              <li><a href="#architecture">Architecture</a></li>
              <li><a href="#features">Celery Pipelines</a></li>
              <li><a href="#security">Security</a></li>
            </ul>
          </div>
          <div className="footer-col">
            <h4>Resources</h4>
            <ul>
              <li><a href="#docs">Documentation</a></li>
              <li><a href="#api">API Reference</a></li>
              <li><a href="#github">GitHub</a></li>
            </ul>
          </div>
          <div className="footer-col">
            <h4>Company</h4>
            <ul>
              <li><a href="#about">About Nexus</a></li>
              <li><a href="#contact">Contact</a></li>
              <li><a href="#legal">Legal</a></li>
              <li><EasterEgg /></li>
            </ul>
          </div>
        </div>
        <div className="footer-bottom">
          <span>&copy; {new Date().getFullYear()} Agent de Gestion Sociale. All rights reserved.</span>
          <span>System Status: Operational</span>
        </div>
      </footer>
    </div>
  );
}
